### ISSUE TITLE
Compilation error in file included from fglm_core

### ISSUE THREAD

**Issue by ShrinivasJC** [algebraic-solving/msolve#190]
I get the following error when I run "make". Not sure if it is due some incompatible library. Any help is greatly appreciated!

<blockquote>
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..    -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4a -msha -maes -mavx -mfma -mavx2 -mrdrnd -mbmi -mbmi2 -madx -mabm -fopenmp -g -O2 -MT libfglm_la-fglm_core.lo -MD -MP -MF .deps/libfglm_la-fglm_core.Tpo -c -o libfglm_la-fglm_core.lo `test -f 'fglm_core.c' || echo './'`fglm_core.c

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4a -msha -maes -mavx -mfma -mavx2 -mrdrnd -mbmi -mbmi2 -madx -mabm -fopenmp -g -O2 -MT libfglm_la-fglm_core.lo -MD -MP -MF .deps/libfglm_la-fglm_core.Tpo -c fglm_core.c  -fPIC -DPIC -o .libs/libfglm_la-fglm_core.o
In file included from fglm_core.c:61:
../upolmat/nmod_mat_poly.h: In function 'nmod_mat_poly_get_entry':
../upolmat/nmod_mat_poly.h:332:29: error: 'nmod_mat_struct' has no member named 'rows'
  332 |    return (matp->coeffs + k)->rows[i][j];
      |                             ^~
../upolmat/nmod_mat_poly.h: In function 'nmod_mat_poly_entry_ptr':
../upolmat/nmod_mat_poly.h:341:29: error: 'nmod_mat_struct' has no member named 'rows'
  341 |    return (matp->coeffs + k)->rows[i] + j;
      |                             ^~
../upolmat/nmod_mat_poly.h: In function 'nmod_mat_poly_set_entry':
../upolmat/nmod_mat_poly.h:324:28: error: 'nmod_mat_struct' has no member named 'rows'
  324 |     (((matp)->coeffs + (k))->rows[(i)][(j)])
      |                            ^~
../upolmat/nmod_mat_poly.h:351:5: note: in expansion of macro 'nmod_mat_poly_entry'
  351 |     nmod_mat_poly_entry(matp, k, i, j) = x;
      |     ^~~~~~~~~~~~~~~~~~~
../upolmat/nmod_mat_poly.h: In function 'nmod_mat_poly_permute_rows':
../upolmat/nmod_mat_poly.h:440:41: error: 'nmod_mat_struct' has no member named 'rows'
  440 |             mat_tmp[i] = matp->coeffs[k].rows[perm_act[i]];
      |                                         ^
../upolmat/nmod_mat_poly.h:442:28: error: 'nmod_mat_struct' has no member named 'rows'
  442 |             matp->coeffs[k].rows[i] = mat_tmp[i];
      |                            ^
../upolmat/nmod_mat_poly_set_from.c: In function 'nmod_mat_poly_set_trunc_from_poly_mat':
../upolmat/nmod_mat_poly.h:324:28: error: 'nmod_mat_struct' has no member named 'rows'
  324 |     (((matp)->coeffs + (k))->rows[(i)][(j)])
      |                            ^~
../upolmat/nmod_mat_poly_set_from.c:67:17: note: in expansion of macro 'nmod_mat_poly_entry'
   67 |                 nmod_mat_poly_entry(matp, k, i, j) = nmod_poly_get_coeff_ui(nmod_poly_mat_entry(pmat, i, j), k);
      |                 ^~~~~~~~~~~~~~~~~~~
In file included from fglm_core.c:65:
../upolmat/nmod_mat_poly_mbasis.c: In function 'nmod_mat_poly_mbasis':
../upolmat/nmod_mat_poly_mbasis.c:222:72: error: 'nmod_mat_struct' has no member named 'rows'
  222 |                 if (!_nmod_vec_is_zero(appbas->coeffs[appbas->length-1].rows[i], m))
      |                                                                        ^
../upolmat/nmod_mat_poly_mbasis.c:234:69: error: 'nmod_mat_struct' has no member named 'rows'
  234 |                 save_zero_rows[i] = appbas->coeffs[appbas->length-1].rows[i];
      |                                                                     ^
../upolmat/nmod_mat_poly_mbasis.c:235:49: error: 'nmod_mat_struct' has no member named 'rows'
  235 |                 appbas->coeffs[appbas->length-1].rows[i] = appbas->coeffs[appbas->length-2].rows[i];
      |                                                 ^
../upolmat/nmod_mat_poly_mbasis.c:235:92: error: 'nmod_mat_struct' has no member named 'rows'
  235 |                 appbas->coeffs[appbas->length-1].rows[i] = appbas->coeffs[appbas->length-2].rows[i];
      |                                                                                            ^
../upolmat/nmod_mat_poly_mbasis.c:240:38: error: 'nmod_mat_struct' has no member named 'rows'
  240 |                     appbas->coeffs[d].rows[i] = appbas->coeffs[d-1].rows[i];
      |                                      ^
../upolmat/nmod_mat_poly_mbasis.c:240:68: error: 'nmod_mat_struct' has no member named 'rows'
  240 |                     appbas->coeffs[d].rows[i] = appbas->coeffs[d-1].rows[i];
      |                                                                    ^
../upolmat/nmod_mat_poly_mbasis.c:243:34: error: 'nmod_mat_struct' has no member named 'rows'
  243 |                 appbas->coeffs[0].rows[i] = save_zero_rows[i];
      |                                  ^
../upolmat/nmod_poly_mat_utils.c: In function 'nmod_poly_mat_set_trunc_from_mat_poly':
../upolmat/nmod_mat_poly.h:324:28: error: 'nmod_mat_struct' has no member named 'rows'
  324 |     (((matp)->coeffs + (k))->rows[(i)][(j)])
      |                            ^~
../upolmat/nmod_poly_mat_utils.c:54:62: note: in expansion of macro 'nmod_mat_poly_entry'
   54 |                 nmod_poly_mat_entry(pmat, i, j)->coeffs[k] = nmod_mat_poly_entry(matp, k, i, j);
      |                                                              ^~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:436: libfglm_la-fglm_core.lo] Error 1
make[2]: Leaving directory '/home/shrinivas/Documents/Softwares/msolve/src/fglm'
make[1]: *** [Makefile:1259: all-recursive] Error 1
make[1]: Leaving directory '/home/shrinivas/Documents/Softwares/msolve'
make: *** [Makefile:1000: all] Error 2
<blockquote>

**Comment by jerebertho** [comment]
Hi,

Thanks for the report. Can you tell us which version of FLINT you are using?
If possible, could you try with [FLINT  v3.1.3-p1](https://github.com/flintlib/flint/releases/tag/v3.1.3-p1)?

Best,
Jérémy

**Comment by vneiger** [comment]
Most likely, you have a version of FLINT which is quite recent, compiled in the last few weeks. There has been a change in the data structure for matrices, see https://github.com/flintlib/flint/pull/2162 . This change will be reflected in msolve at some point, and we will ensure msolve works well with FLINT 3.2.0 (which is currently at the "release candidate" stage, if I am not mistaken), but in the meantime, please compile msolve against an earlier version of FLINT such as the one pointed to by Jérémy.

**Comment by ShrinivasJC** [comment]
Thank you for the quick reply! Compilation works with FLINT v3.1.3-p1. 

I however now have issue with library linking

>./test/diff/diff_nf_31.sh
/home/Softwares/msolve/.libs/msolve: error while loading shared libraries: libflint.so.19: cannot open shared object file: No such file or directory

**Comment by vneiger** [comment]
@ShrinivasJC  code was just merged, that should solve the issue. In other words, you should now be able to compile msolve against the development version of FLINT (it should also compile against FLINT v3.2.1, if you prefer). Thanks for raising the issue!
